### ISSUE TITLE
Show status of game beneath board

### ISSUE THREAD

**Issue by Matttaylor8910** [Matttaylor8910/codetango#38]
During the game, we should tell the users what they can do:

If player:
- If your turn:
  - "Waiting for spymaster to give clue"
  - "You can take up to (n + 1) clues"
    - Keep track of the guesses for the current given clue
- If not your turn:
  - "Waiting for the other team"
If spymaster:
- If your turn:
  - "Give your team a clue"
- If not your turn:
  - "Waiting for the other team"

**Comment by bacontech** [comment]
complete
